# PickupWatcher config
#
# Messages
#     message_single - Message to display when a single item is picked up. Use %item% as placeholder for item name.
#        Supports color codes.
#     message_multiple - Message to display when a stack of items is picked up. Use %item% as placeholder for item name
#        and %amount% as placeholder for amount of items. Supports color codes.
#     message_location - Where to display the message. Allowed values: ACTIONBAR - action bar, above hotbar; CHAT -
#        in chat, this can get crowded.
#     queue_delay - number of seconds in between sending queued messages. May need to increase this value if using
#        ACTIONBAR messages, as sometimes the action bar will eat sequential messages.
#
# muted_players - list of UUIDs of players who have muted pickup messages.

messages:
    message_single: "&ePicked up %item%"
    message_multiple: "&ePicked up %item% (%amount%)"
    message_location: ACTIONBAR
    queue_delay: 3
muted_players: []