name: PickupWatcher
description: Bukkit plugin to alert users about item pickups.
author: Baphomet Media
website: baph.xyz
api-version: 1.21
version: 2.1.1
main: xyz.baph.PickupWatcher.PickupWatcher

commands:
    pickup:
        description: Main plugin command
        usage: /pickup (subcommand)
        aliases: [pw, pickupwatcher]
permissions:
    pickupwatcher.mute:
        description: Allows muting pickup notifications
        default: true
    pickupwatcher.reload:
        description: Allows reloading plugin configs
        default: OP